# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenConnectKtor < Formula
  desc "Protoc plugin to generate Ktor server code"
  homepage "https://github.com/ichizero/connect-ktor"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.0.7/connect-ktor_Darwin_x86_64.tar.gz"
      sha256 "f146fce96f0fa413c7f3229fe5e3a363b44cdcb9aa2dba29830184f2a0c6db86"

      def install
        bin.install "protoc-gen-connect-ktor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.0.7/connect-ktor_Darwin_arm64.tar.gz"
      sha256 "451405c19429da1924503c17e5cf5a024501a531b09d464704c178704a3534e7"

      def install
        bin.install "protoc-gen-connect-ktor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ichizero/connect-ktor/releases/download/v0.0.7/connect-ktor_Linux_x86_64.tar.gz"
        sha256 "20e914ce4e0f99fb4f19c7aa43e21095700c4f7e1ef2087578a54fa69f3cd4e7"

        def install
          bin.install "protoc-gen-connect-ktor"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ichizero/connect-ktor/releases/download/v0.0.7/connect-ktor_Linux_arm64.tar.gz"
        sha256 "e48622771665af0135dca8620a9be6800afb214adfad4920327dcecefb2113ad"

        def install
          bin.install "protoc-gen-connect-ktor"
        end
      end
    end
  end
end
