# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenConnectKtor < Formula
  desc "Protoc plugin to generate Ktor server code"
  homepage "https://github.com/ichizero/connect-ktor"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.2.0/connect-ktor_Darwin_x86_64.tar.gz"
      sha256 "db97f1e3dabd2b6848f87366e4d7e0e4cfca675083e2b05d8ed551c5ca33471c"

      define_method(:install) do
        bin.install "protoc-gen-connect-ktor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.2.0/connect-ktor_Darwin_arm64.tar.gz"
      sha256 "b53dea3e6d4fb12ecfd4ce2fa1f4f14d90836ccdb821a068c8f21b5cf9bec13d"

      define_method(:install) do
        bin.install "protoc-gen-connect-ktor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.2.0/connect-ktor_Linux_x86_64.tar.gz"
      sha256 "617884bf68e88a2150ea1947743a15844de253aa8d9c190770eccd113071bdae"
      define_method(:install) do
        bin.install "protoc-gen-connect-ktor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ichizero/connect-ktor/releases/download/v0.2.0/connect-ktor_Linux_arm64.tar.gz"
      sha256 "0e3628496c4f519826dec8923343291f6fe1cfbe6340fee7cfcee084f3b3ce2c"
      define_method(:install) do
        bin.install "protoc-gen-connect-ktor"
      end
    end
  end
end
